<div class="container text-center">
    <?php if (isset($_SESSION['email']) && $_SESSION['email'] === 'web2@gmail.com'): ?>
        <h2>Agregar Nueva Sede</h2>
        <form action="<?php echo BASE_URL . 'agregarSede/'; ?>" method="POST">
            <div class="mb-3">
                <label for="pais" class="form-label">País:</label>
                <input type="text" class="form-control" id="pais" name="pais" required>
            </div>
            <div class="mb-3">
                <label for="ciudad" class="form-label">Ciudad:</label>
                <input type="text" class="form-control" id="ciudad" name="ciudad" required>
            </div>
            <button type="submit" class="btn btn-primary w-100">Agregar Sede</button>
        </form>
        <h2 class="mt-5">Editar o Borrar Sedes</h2>
        <ol class="list-group list-group-numbered">
            <?php foreach ($sedes as $sede): ?>
                <li class="list-group-item d-flex justify-content-between align-items-start">
                    <div class="ms-2 me-auto">
                        <div class="fw-bold"><?php echo htmlspecialchars($sede->ciudad . ", " . $sede->pais); ?></div>
                    </div>
                    <div class="d-flex">
                    <a href="<?php echo BASE_URL . 'editarSede/' . $sede->id_sede; ?>" class="btn btn-warning me-2 w-100">Editar</a>
                    <form action="<?php echo BASE_URL . 'eliminarSede/'; ?>" method="POST" style="display:inline;">
                            <input type="hidden" name="id_sede" value="<?php echo $sede->id_sede; ?>">
                            <button type="submit" class="btn btn-danger w-100">Borrar</button>
                        </form>
                    </div>
                </li>
            <?php endforeach; ?>
        </ol>
    <?php else: ?>
        <p>No tienes permiso para acceder a esta sección.</p>
    <?php endif; ?>
    <?php include './templates/footer.phtml'; ?>
</div>
