<?php require_once './templates/header.phtml'; ?>


<div class="container">
    <h2 class="h2">sumandote ganas una experiencia unica</h2>
    <form method="POST" action="signup">
        <div class="mb-3">
            <label for="exampleInputEmail1" class="form-label">Cuenta de email</label>
            <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
        </div>
        <div class="mb-3">
            <label for="nombre" class="form-label">nombre</label>
            <input type="text" class="form-control" id="nombre" aria-describedby="emailHelp">
        </div>

        <div class="mb-3">
            <label for="apellido" class="form-label">apellido</label>
            <input type="text" class="form-control" id="apellido" aria-describedby="emailHelp">
        </div>
        <div class="mb-3">
            <label for="exampleInputPassword1" class="form-label">Contraseña</label>
            <input type="password" class="form-control" id="exampleInputPassword1">
        </div>
        <div class="mb-3 form-check">
            <input type="checkbox" class="form-check-input" id="exampleCheck1">
            <label class="form-check-label" for="exampleCheck1">recordarme</label>
        </div>
        <button type="submit" class="btn btn-primary">Enviar</button>
    </form>
</div>


<?php require_once './templates/footer.phtml'; ?>