<?php require_once './templates/header.phtml'; ?>
<div class="container text-center">
    <div class="row">
        <div class="col">
            <img src="imagenes/voluntariado.jpg" alt="" class="img-fluid d-block w-100 img-tamano">
        </div>
        <div class=" col">
            <img src="imagenes/voluntariado3.jpg" alt="" class="img-fluid d-block w-100 img-tamano">
        </div>
        <div class=" col">
            <img src="imagenes\voluntariado2.jpg" alt="" class="img-fluid d-block w-100 img-tamano">

        </div>
    </div>
</div>
</div>
<?php require_once './templates/formAdmin.php'; ?>

<figure class="text-center">
    <blockquote class="blockquote">
        <p>Que esperas para sumarte?</p>
    </blockquote>
    <figcaption class="blockquote-footer">
        una experiencia unica en la vida
    </figcaption>
</figure>
<div class="container">

    <table class="table">
        <thead>
            <tr>
                <th scope="col">voluntario</th>
                <th scope="col">nombre</th>
                <th scope="col">apellido</th>
                <th scope="col">sede</th>
            </tr>
        </thead>
        <tbody class="table-group-divider">
            <?php foreach ($voluntarios as $voluntario): ?>
                <tr>
                    <th scope="row"><?= htmlspecialchars($voluntario->id_voluntario) ?></th>
                    <td><?= htmlspecialchars($voluntario->nombre) ?></td>
                    <td><?= htmlspecialchars($voluntario->apellido) ?></td>
                    <td><?= htmlspecialchars($voluntario->sede_nombre) ?></td>
                    <!-- Mostrar botones de editar y eliminar si es administrador -->
                    <td><a class="btn btn-primary" href="editarVoluntario/<?= $voluntario->id_voluntario ?>" role="button">Editar</a></td>
                    <td><a class="btn btn-primary" href="eliminarVoluntario/<?= $voluntario->id_voluntario ?>" role="button">Eliminar</a></td>
                </tr>
            <?php endforeach; ?>
        </tbody>

    </table>
</div>
<?php include_once './templates/footer.phtml'; ?>