<?php require_once './templates/header.phtml'; ?>

<div class="container text-center">
    <div class="row">
        <div class="col">
            <img src="imagenes/voluntariado.jpg" alt="" class="img-fluid d-block w-100 img-tamano">
        </div>
        <div class=" col">
            <img src="imagenes/voluntariado3.jpg" alt="" class="img-fluid d-block w-100 img-tamano">
        </div>
        <div class=" col">
            <img src="imagenes\voluntariado2.jpg" alt="" class="img-fluid d-block w-100 img-tamano">

        </div>
    </div>
</div>